[symlinks]
aerospace = "/Users/benjaminch/.aerospace.toml"
"ghostty/config" = "/Users/benjaminch/.config/ghostty/config"
gitconfig = "/Users/benjaminch/.gitconfig"
"k9s/config.yml" = "/Users/benjaminch/.config/k9s/config.yml"
"lazygit/config.yml" = "/Users/benjaminch/.config/lazygit/config.yml"
"nvim/.gitignore" = "/Users/benjaminch/.config/nvim/.gitignore"
"nvim/.neoconf.json" = "/Users/benjaminch/.config/nvim/.neoconf.json"
"nvim/LICENSE" = "/Users/benjaminch/.config/nvim/LICENSE"
"nvim/README.md" = "/Users/benjaminch/.config/nvim/README.md"
"nvim/init.lua" = "/Users/benjaminch/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "/Users/benjaminch/.config/nvim/lazy-lock.json"
"nvim/lazyvim.json" = "/Users/benjaminch/.config/nvim/lazyvim.json"
"nvim/lua/config/autocmds.lua" = "/Users/benjaminch/.config/nvim/lua/config/autocmds.lua"
"nvim/lua/config/keymaps.lua" = "/Users/benjaminch/.config/nvim/lua/config/keymaps.lua"
"nvim/lua/config/lazy.lua" = "/Users/benjaminch/.config/nvim/lua/config/lazy.lua"
"nvim/lua/config/options.lua" = "/Users/benjaminch/.config/nvim/lua/config/options.lua"
"nvim/lua/plugins/debug.lua" = "/Users/benjaminch/.config/nvim/lua/plugins/debug.lua"
"nvim/lua/plugins/example.lua" = "/Users/benjaminch/.config/nvim/lua/plugins/example.lua"
"nvim/lua/plugins/go.lua" = "/Users/benjaminch/.config/nvim/lua/plugins/go.lua"
"nvim/lua/plugins/neo-tree.lua" = "/Users/benjaminch/.config/nvim/lua/plugins/neo-tree.lua"
"nvim/lua/plugins/test.lua" = "/Users/benjaminch/.config/nvim/lua/plugins/test.lua"
"nvim/stylua.toml" = "/Users/benjaminch/.config/nvim/stylua.toml"
"skhd/skhdrc" = "/Users/benjaminch/.config/skhd/skhdrc"
starship = "/Users/benjaminch/starship"
tmux = "/Users/benjaminch/.tmux"
wezterm = "/Users/benjaminch/.wezterm"
"zellij/config.kdl" = "/Users/benjaminch/.config/zellij/config.kdl"
zshenv = "/Users/benjaminch/.zshenv"
zshrc = "/Users/benjaminch/.zshrc"

[templates]
